### ISSUE TITLE
No module named 'exists_redis'

### ISSUE THREAD

**Issue by hhsecond** [RedisLabsModules/RLTest#52]
Tests are broken because it rltest couldn't find `exists_redis`. Full stack trace
```bash
Traceback (most recent call last):
  File "/home/hhsecond/anaconda3/envs/redisai/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/hhsecond/anaconda3/envs/redisai/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/hhsecond/anaconda3/envs/redisai/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/hhsecond/anaconda3/envs/redisai/lib/python3.7/site-packages/RLTest/__init__.py", line 1, in <module>
    from RLTest.env import Env
  File "/home/hhsecond/anaconda3/envs/redisai/lib/python3.7/site-packages/RLTest/env.py", line 15, in <module>
    from .redis_enterprise_cluster import EnterpriseRedisClusterEnv
  File "/home/hhsecond/anaconda3/envs/redisai/lib/python3.7/site-packages/RLTest/redis_enterprise_cluster.py", line 3, in <module>
    from exists_redis import ExistsRedisEnv
ModuleNotFoundError: No module named 'exists_redis'
```

**Comment by MeirShpilraien** [comment]
Should fix it:
https://github.com/RedisLabsModules/RLTest/pull/53

**Comment by hhsecond** [comment]
This is fixed. Thanks
